### ISSUE TITLE
Packaging problem?

### ISSUE THREAD

**Issue by mykter** [kaa/gulp-apply-patch#3]
When I try and use this as-is, it fails with `through.obj is not a function`. I think this is because some other package in my node_modules has installed an older version of through2. If I explicitly go into `node_modules/gulp-apply-patch` and run `npm install`, it then works.

I'm not too familiar with npm packages, but this look like a packaging problem? I can see that package.json correctly specifies a recent version of through2.

**Comment by kaa** [comment]
It's a little difficult to track down based only on the information provided. I've found from personal experience that npm can get its bits in a tangle sometimes and just deleting `node_modules` and `npm install` again often solves these issues.

Does the problem persist after a reinstall of the `node_modules` directory? If not, what version gets installed in `gulp-apply-patch`s `node_modules` for you?

**Comment by mykter** [comment]
Thanks for the quick response. `rm -rf node_modules` was my first port of call, but it didn't help.

>what version gets installed in gulp-apply-patchs node_modules for you?

Aha, that looks like the problem - there is no node_modules subdirectory under gulp-apply-patch. I  installed without --save-dev as I was testing it out - looks like that is the problem. With --save-dev all is well.

Thanks for the module by the way!

**Comment by mykter** [comment]
I wrote about how this package helped me here: http://mykter.com/2018/02/09/patching-node-packages

**Comment by kaa** [comment]
Wow, that's a great and thorough study of an often overlooked looked problem.

Thanks for reconnecting!
